---
title: "HTA_VIH"
author: "ALE Junior"
date: '2022-06-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading libraries}
pacman::p_load(
  tidyverse,
  readxl
)
```


```{r import data}
hta_vih <- read_excel("hta_vih.xlsx")
glimpse(hta_vih)          
```

```{r data recocoding }
hta <- hta_vih %>% 
  rename(
      id_depart = `MNT_odk-I-I1`,
      centre = `MNT_odk-I-I2`,
      id_enq = `MNT_odk-I-I3`,
      num_enr = `MNT_odk-I-serial_num`,
      date = `MNT_odk-I-I4`,
      sexe = `MNT_odk-S-S1`,
      age = `MNT_odk-S-S2`,
      niv_instr = `MNT_odk-S-S3`,
      ethnie = `MNT_odk-S-S4`,
      etat_civil = `MNT_odk-S-S5`,
      ctg_sociopro = `MNT_odk-S-S6`,
      tabagisme = `MNT_odk-M1`,
      alcool = `MNT_odk-M7`,
      nbre_jrs_cons_fruit = `MNT_odk-MHA-M11`,
      nbre_port_fruit_jrs = `MNT_odk-MHA-M12`,
      nbre_jrs_cons_leg = `MNT_odk-MHA-M13`,
      nbre_port_leg_jrs = `MNT_odk-MHA-M14`,
      freq_ajt_sel = `MNT_odk-MSA-M15`,
      freq_cons_plat_sel = `MNT_odk-MSA-M16`,
      act_phsq_travail = `MNT_odk-MAP-M18`,
      act_phsq_dpl = `MNT_odk-MAP-M20`,
      act_phsq_loisir = `MNT_odk-MAP-M23`,
      duree_ass_couch_jr = `MNT_odk-MAP-M25`,
      ant_hta = `MNT_odk-AHTA-A1`,
      trat_mod_hta = `MNT_odk-AHTA-A2`,
      trat_trad_hta = `MNT_odk-AHTA-A3`,
      ant_diabete = `MNT_odk-AD-A4`,
      trat_mod_diabete = `MNT_odk-AD-A5`,
      trat_trad_diabete = `MNT_odk-AD-A6`,
      ant_hchol = `MNT_odk-ACE-A7`,
      trat_mod_hchol = `MNT_odk-ACE-A8`,
      trat_trad_hchol = `MNT_odk-ACE-A9`,
      ant_card = `MNT_odk-AMC-A10`,
      aspir_proph = `MNT_odk-AMC-A11`,
      statine = `MNT_odk-AMC-A12`,
      depression = `MNT_odk-D-D1`,
      fatigue = `MNT_odk-D-D2`,
      dim_interet = `MNT_odk-D-D3`,
      gn_pert_pds = `MNT_odk-D-D4`,
      insm_hysm = `MNT_odk-D-D5`,
      agt_rlt_psych = `MNT_odk-D-D6`,
      ftg_pert_eng = `MNT_odk-D-D7`,
      devalorisation = `MNT_odk-D-D8`,
      dim_apt_penser = `MNT_odk-D-D9`,
      idee_mort = `MNT_odk-D-D10`,
      ronflement_fort = `MNT_odk-DS-D11`,
      ftg_sml = `MNT_odk-DS-D12`,
      arret_resp_noct = `MNT_odk-DS-D13`,
      hta = `MNT_odk-DS-D14`,
      tour_cou_imp = `MNT_odk-DS-D17`,
      tas = `MNT_odk-P-P1_1`,
      tad = `MNT_odk-P-P1_2`,
      enceinte = `MNT_odk-P-P2`,
      taille = `MNT_odk-P-P3`,
      poids = `MNT_odk-P-P4`,
      tour_taille = `MNT_odk-P-P5`,
      tour_hanche = `MNT_odk-P-P6`,
      pouls = `MNT_odk-P-P7`,
      an_depsg = `MNT_odk-V-V1`,
      date_debut = `debarv`,
      stde_vih = `MNT_odk-V-V4`,
      trtment_arv_1 = `arv1`,
      trtment_arv_2 = `arv2`,
      trtment_arv_3 = `arv3`,
      trtment_arv_4 = `arv4`,
      trtment_arv_5 = `arv5`,
      echec_imun = `MNT_odk-V-V6`,
      echec_virol = `MNT_odk-V-V7`,
      ext_exm_paracl = `MNT_odk-E-E1`,
      dte_realisation = `MNT_odk-E-E2`,
      glycemie = `MNT_odk-E-E3`,
      hgb_glyquee = `MNT_odk-E-E4`,
      chl_total = `MNT_odk-E-E5`,
      chl_hdl = `MNT_odk-E-E6`,
      chl_ldl = `MNT_odk-E-E7`,
      triglycerides = `MNT_odk-E-E8`,
      uree = `MNT_odk-E-E9`,
      creatinine = `MNT_odk-E-E10`
       ) %>% 
  mutate( 
       tailm = taille / 100,
       imc = round(poids / (tailm * tailm),2),
        imc_c = factor(
          ifelse(
            imc < 18.5, "underweight",
            ifelse(imc < 25 & imc > 18.5, "normal weight", "overweight and obese"))),
       
       hta = factor(
         ifelse(
           hta == 0, "no", "yes")
         ),
       trat_mod_hta = factor(
         ifelse(
           trat_mod_hta == 0, "no", "yes")
         ),
       hta_c = factor(
            ifelse(
              tas > 129 & tad > 79 | hta == "yes" | trat_mod_hta == "yes" , "hta", "non hta")
       ),
            sexe = factor(
              ifelse(
                sexe == 1, "homme", "femme")
              ),
       tabagisme = factor(
         ifelse(
           tabagisme == 0, "no fumeur",
           ifelse(tabagisme == 1, "ancien fumeur", "fumeur actuel"))
       ),
       alcool = factor(
         ifelse(
           alcool == 0, "no buveur",
           ifelse(alcool == 1, "ancien buveur", "buveur actuel"))
       ),
       ethnie = factor(
         ifelse(
           ethnie == 1, "fon",
           ifelse( ethnie == 2, "adja",
                   ifelse(ethnie == 3, "yoruba",
                          ifelse(ethnie == 4, "bariba",
                                 ifelse(ethnie == 5, "dendi",
                                        ifelse(ethnie == 6, "peulh",
                                               ifelse(ethnie == 7, "yoa",
                                                      ifelse(ethnie == 8, "otamarie",
                                                             ifelse(ethnie == 9, "autre", "non repondu")))))))))
         ),
       niv_instr = factor(
         ifelse(
           niv_instr == 1, "aucun",
           ifelse( niv_instr == 2, "primaire",
                   ifelse(niv_instr == 3, "secondaire",
                          ifelse(niv_instr == 4, "universitaire", "non repondu"))))
         ),
       ctg_sociopro = factor(
         ifelse(
           ctg_sociopro == 1, "employe etat",
           ifelse( ctg_sociopro == 2, "employe prive",
                   ifelse(ctg_sociopro == 3, "independant",
                          ifelse(ctg_sociopro == 4, "benevole",
                                 ifelse(ctg_sociopro == 5, "etudiant",
                                        ifelse(ctg_sociopro == 6, "maitresse maison",
                                               ifelse(ctg_sociopro == 7, "retraite",
                                                      ifelse(ctg_sociopro == 8, "chomeur",
                                                             ifelse(ctg_sociopro == 9, "invalide", "refusee")))))))))
       ),
       stde_vih = factor(
         ifelse(
           stde_vih == 1, "stade 1",
           ifelse( stde_vih == 2, "stade 2",
                   ifelse(stde_vih == 3, "stade 3", "stade 4")))
         ),
            )
glimpse(hta)

```
```{r Characteristics of the study participants}
a <- table(hta$sexe)
prop.table(a)

summary(hta$age)
table(hta$age < 42)



```
```{r prevalence of overweight and obesity}
summary(hta$imc)

indice <- table(hta$imc_c)
indice
prop.table(indice) * 100

ggplot(data = hta) + 
  geom_bar(mapping = aes(x = imc_c, fill = sexe), position = "dodge")
```

```{r categorisation of hypertension}

hyper <- table(hta$hta_c)
hyper
prop.table(hyper) * 100


hyp <- table(hta$hta)
prop.table(hyp) * 100

table(hta$ant_hta)
prop.table(table(hta$ant_hta)) * 100

table(hta$enceinte)
```


```{r Factor associated with overweight and obesity}
logit <- glm(
  formula = hta_c ~ age + 
    sexe + 
    tabagisme + 
    alcool +
    niv_instr +
    imc_c + 
    pouls + 
    stde_vih, 
  data = hta, family = "binomial")
summary(logit)
```









